# Generated by Django 4.0 on 2022-01-25 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='article_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_slides', to='sample.article'),
        ),
    ]
