# Generated by Django 4.0 on 2022-01-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_slide_article_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='description',
        ),
    ]
