# Generated by Django 4.0 on 2022-02-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Anime', 'Anime'), ('Sports', 'Sports'), ('Hollyhood', 'Hollyhood'), ('Bollyhood', 'Bollyhood'), ('Sports', 'Sports'), ('Netflix', 'Netflix')], default='Unknown', max_length=20),
        ),
    ]
