# Generated by Django 4.0 on 2022-02-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='xx', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Sports', 'Sports'), ('Hollywood', 'Hollywood'), ('Bollywood', 'Bollywood'), ('Netflix', 'Netflix')], default='Unknown', max_length=20),
        ),
    ]
