# Generated by Django 4.0 on 2022-02-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_rename_relevant_url_article_relevant_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=2000, unique=True),
        ),
    ]
