# Generated by Django 4.0 on 2022-02-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
