# Generated by Django 4.0 on 2022-02-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0014_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='xx', max_length=2000, unique=True),
            preserve_default=False,
        ),
    ]
