# Generated by Django 4.0 on 2022-02-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0015_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Sports', 'Sports'), ('Hollywood', 'Hollywood'), ('Bollywood', 'Bollywood'), ('Netflix', 'Netflix')], default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='relevant_img_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=7000, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
